# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        files: '.*/scripts/.*\.(py|sh)$'
    -   id: end-of-file-fixer
        files: '.*/scripts/.*\.(py|sh)$'
    -   id: check-yaml
        files: '.*/scripts/.*\.(py|sh)$'

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.12
        files: '.*/scripts/.*\.(py|sh)$'
